#!/usr/bin/env groovy

@Library('jenkins-shared-library')       #(underscore is necessary if you donot use def gv)
def gv

pipeline {
    agent any
    tools {
       maven 'Maven'
    }
    stages {
        stage("init"){
            steps {
                script {
                    gv = load "script.groovy"
                }
            }
        }
        stage("build jar"){
            steps {
                script {
                    buildJar()
                }
            }
        }
        stage("build image"){
            steps {
                script {
                    buildImage 'nanajanashaia/demo-app:jma-2.0'
                }
            }
        }
        stage("deploy"){
            steps {
                script {
                    gv.deploy()
                }
            }
        }


    }
}
